main:
- identifier: 'about'
  name: 'About'
  title: 'About'
  url: /about/
  weight: -4
- identifier: 'projects'
  name: 'Projects'
  title: 'Projects'
  url: /projects/
  weight: -3
- identifier: 'categories'
  name: 'Categories'
  title: 'Categories'
  url: /categories/
  weight: -2
- identifier: 'tags'
  name: 'Tags'
  title: 'Tags'
  url: /Tags/
  weight: -1