baseURL: 'https://blog.darkdell.net/'
languageCode: 'en-us'
title: 'Missing the Point'
theme: 'ananke'
deployment:
  targets:
    - name: 's3'
      URL: 's3://darkdell.blog?region=us-east-1'
      cloudFrontDistributionID: 'E3ACQSNDE8NDOY'
enableGitInfo: yes
enableEmoji: yes
