name: Continuous Deployment
on:
  push:
    branches:
      - main
jobs:

  # Deploy the blog to S3.
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # https://github.com/actions/cache/releases/tag/v3.0.10
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - name: Install Hugo
        run: |
          sudo apt-get update
          sudo apt-get install hugo
      - name: Build site
        run: hugo
      - name: Deploy site
        run: hugo deploy
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${ secrets.AWS_SECRET_ACCESS_KEY }}"
          AWS_DEFAULT_REGION: 'us-east-1'
